FROM node:20-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package.json ./
COPY prisma/schema.prisma prisma/
RUN npm install && npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
