import { OrgChartData } from './types';

export const octOrgData: OrgChartData = {
  root: {
    id: 'daryl-croft',
    name: 'Daryl Croft',
    title: 'CIO, OCT Branch Manager',
    employeeNumber: '271',
    hasLink: true,
    subordinates: [
      {
        id: 'branch-office',
        name: "Branch Manager's Office",
        title: '',
        hasLink: true,
        subordinates: [
          {
            id: 'andrew-clark',
            name: 'Andrew Clark',
            title: 'Strategic Coordinator',
          },
          {
            id: 'charalyn-parlee',
            name: 'Charalyn Parlee',
            title: 'Administrative Assistant',
          },
        ],
      },
      {
        id: 'daniel-pedersen',
        name: 'Daniel Pedersen',
        title: 'Director & Corporate Information Security Officer',
        employeeNumber: '26',
        hasLink: true,
        subordinates: [
          {
            id: 'andrea-buchholz',
            name: 'Andrea Buchholz',
            title: 'PgM, Continuity & Recovery Services, Directory Services, IAM Ops',
            employeeNumber: '7',
            hasLink: true,
          },
          {
            id: 'david-malone',
            name: 'David Malone',
            title: 'PgM, Access Management/ EIAM',
            employeeNumber: '4',
            hasLink: true,
          },
          {
            id: 'jack-truong',
            name: 'Jack Truong',
            title: 'PgM, Cybersecurity Investigation, Incident Response, Assurance and SecOps',
            employeeNumber: '5',
            hasLink: true,
          },
          {
            id: 'kevin-mckay',
            name: 'Kevin McKay',
            title: 'PgM, Governance, Risk, Compliance & Awareness',
            employeeNumber: '6',
            hasLink: true,
          },
          {
            id: 'greg-krol',
            name: 'Greg Krol',
            title: 'PgM, Technology Infrastructure Operations - 141406',
            employeeNumber: '23',
            hasLink: true,
          },
          {
            id: 'josh-mcgillis',
            name: 'Josh McGillis',
            title: 'PgM, Data Technology - 503295',
            employeeNumber: '24',
            hasLink: true,
          },
        ],
      },
      {
        id: 'mike-fryer',
        name: 'Mike Fryer',
        title: 'Director, Integrated Technology Solutions - 1002067',
        employeeNumber: '90',
        hasLink: true,
        subordinates: [
          {
            id: 'tim-hoffman',
            name: 'Tim Hoffman',
            title: 'PgM, Partner Experience - 1003453',
            employeeNumber: '23',
            hasLink: true,
          },
          {
            id: 'kevin-wang',
            name: 'Kevin Wang',
            title: 'Technical Lead, ITS - 130383',
            employeeNumber: '3',
          },
          {
            id: 'alex-noot',
            name: 'Alex Noot',
            title: 'PgM, Service Delivery & Analytics - 112464',
            employeeNumber: '12',
            hasLink: true,
          },
        ],
      },
      {
        id: 'troy-murray',
        name: 'Troy Murray',
        title: 'Director, Technology Planning',
        employeeNumber: '37',
        hasLink: true,
        subordinates: [
          {
            id: 'romelia-fernandez',
            name: 'Romelia Fernandez',
            title: 'PgM, Tech Investment & Financial Mgt',
            employeeNumber: '5',
            hasLink: true,
          },
          {
            id: 'liza-wong',
            name: 'Liza Wong',
            title: 'PgM, Business Engagement',
            employeeNumber: '6',
            hasLink: true,
          },
          {
            id: 'mike-meraw',
            name: 'Mike Meraw',
            title: 'PgM, Vendor & Asset Enablement',
            employeeNumber: '21',
            hasLink: true,
          },
          {
            id: 'roddi-potter',
            name: 'Roddi Potter',
            title: 'Enterprise Solutions Architect',
          },
          {
            id: 'liviu-jalba',
            name: 'Liviu Jalba',
            title: 'PgM, Governance & Delivery',
            employeeNumber: '12',
            hasLink: true,
          },
        ],
      },
      {
        id: 'nisreen-hussain',
        name: 'Nisreen Hussain',
        title: 'Director, Technology PMO',
        employeeNumber: '28',
        hasLink: true,
        subordinates: [
          {
            id: 'shengxi-jin',
            name: 'Shengxi Jin',
            title: 'PgM, Strategy & Operations',
            employeeNumber: '12',
            hasLink: true,
          },
          {
            id: 'auralee-flaman',
            name: 'AuraLee Flaman',
            title: '',
          },
          {
            id: 'deanna-hunter',
            name: 'Deanna Hunter',
            title: '',
          },
          {
            id: 'matthew-raven',
            name: 'Matthew Raven',
            title: 'Program Manager',
            employeeNumber: '37',
            hasLink: true,
          },
        ],
      },
      {
        id: 'robert-dufresne',
        name: 'Robert Dufresne',
        title: 'Director, Application Technology Services',
        employeeNumber: '55',
        hasLink: true,
        subordinates: [
          {
            id: 'margaret-cieslak-olmos',
            name: 'Margaret Cieslak-Olmos',
            title: 'Program Manager',
            employeeNumber: '27',
            hasLink: true,
          },
          {
            id: 'steven-farrants',
            name: 'Steven K Farrants',
            title: '',
          },
          {
            id: 'cory-motsch',
            name: 'Cory Motsch',
            title: 'Domain Architect',
          },
          {
            id: 'ken-merkel',
            name: 'Ken Merkel',
            title: 'Program Manager',
            employeeNumber: '14',
            hasLink: true,
          },
        ],
      },
    ],
  },
};
