import { Transaction, TransactionStatus, DeploymentStatus, BudgetType } from './types';

export const PROGRAMS = ['Data Technology', 'Infrastructure', 'Cybersecurity', 'Enterprise Apps', 'Cloud Operations'];
export const TEAMS = ['Network', 'Server', 'Database', 'Security', 'DevOps', 'End User Computing'];
export const CATEGORIES = ['Hardware Purchase', 'Software License', 'Professional Services', 'Cloud Consumption', 'Maintenance', 'SaaS Subscription', 'Travel & Training'];
export const YEARS = [2023, 2024, 2025, 2026];

export const GOOGLE_SHEET_CSV_URL = 'https://docs.google.com/spreadsheets/d/1jahJDIAiR5-rGrFpUTtj82RjeTh_yv1oNsaoRQCqmbI/export?format=csv';

// Helper to generate IDs
const uuid = () => Math.random().toString(36).substring(2, 9);

export const MOCK_TRANSACTIONS: Transaction[] = [
    {
        id: uuid(),
        program: 'Data Technology',
        team: 'Network',
        category: 'Hardware Purchase',
        nwaNumber: 'NWA-1001',
        projectName: 'Data Center Upgrade Phase 1',
        woNumber: 'WO-9981',
        poNumber: 'PO-5512',
        amountApproved: 150000,
        amountSpent: 142000,
        purchaseYear: 2024,
        status: TransactionStatus.ACTUAL_SAP,
        deploymentStatus: DeploymentStatus.COMPLETED,
        budgetType: BudgetType.CAPITAL,
        createdAt: new Date().toISOString(),
    },
    {
        id: uuid(),
        program: 'Infrastructure',
        team: 'Server',
        category: 'Hardware Purchase',
        nwaNumber: 'NWA-1002',
        projectName: 'Storage Area Network Expansion',
        woNumber: 'WO-9982',
        poNumber: 'PO-5513',
        amountApproved: 85000,
        amountSpent: 40000,
        purchaseYear: 2024,
        status: TransactionStatus.ACTUAL_SAP,
        deploymentStatus: DeploymentStatus.IN_PROGRESS,
        budgetType: BudgetType.CAPITAL,
        createdAt: new Date().toISOString(),
    },
    {
        id: uuid(),
        program: 'Cybersecurity',
        team: 'Security',
        category: 'Software License',
        nwaNumber: 'NWA-2001',
        projectName: 'Firewall Renewal',
        woNumber: 'WO-9100',
        poNumber: 'PO-6001',
        amountApproved: 50000,
        amountSpent: 50000,
        purchaseYear: 2025,
        status: TransactionStatus.PLANNED,
        deploymentStatus: DeploymentStatus.NOT_STARTED,
        budgetType: BudgetType.OPERATING,
        createdAt: new Date().toISOString(),
    },
    {
        id: uuid(),
        program: 'Data Technology',
        team: 'Database',
        category: 'Professional Services',
        nwaNumber: 'NWA-1045',
        projectName: 'Oracle Migration Consult',
        woNumber: 'WO-8800',
        poNumber: 'PO-4400',
        amountApproved: 120000,
        amountSpent: 110000,
        purchaseYear: 2024,
        status: TransactionStatus.ACCRUAL,
        deploymentStatus: DeploymentStatus.COMPLETED,
        budgetType: BudgetType.CAPITAL,
        createdAt: new Date().toISOString(),
    },
    {
        id: uuid(),
        program: 'Enterprise Apps',
        team: 'DevOps',
        category: 'Cloud Consumption',
        nwaNumber: 'NWA-3005',
        projectName: 'Q1 Cloud Compute',
        woNumber: 'WO-3001',
        poNumber: 'PO-3001',
        amountApproved: 30000,
        amountSpent: 32000,
        purchaseYear: 2024,
        status: TransactionStatus.CREDIT_CARD,
        deploymentStatus: DeploymentStatus.COMPLETED,
        budgetType: BudgetType.OPERATING,
        createdAt: new Date().toISOString(),
    },
    {
        id: uuid(),
        program: 'Cloud Operations',
        team: 'Server',
        category: 'Maintenance',
        nwaNumber: 'NWA-4100',
        projectName: 'Annual Server Maintenance',
        woNumber: 'WO-4100',
        poNumber: 'PO-7100',
        amountApproved: 25000,
        amountSpent: 0,
        purchaseYear: 2025,
        status: TransactionStatus.PLANNED,
        deploymentStatus: DeploymentStatus.NOT_STARTED,
        budgetType: BudgetType.OPERATING,
        createdAt: new Date().toISOString(),
    },
    {
        id: uuid(),
        program: 'Data Technology',
        team: 'Network',
        category: 'Hardware Purchase',
        nwaNumber: 'NWA-1099',
        projectName: 'Edge Router Replacement',
        woNumber: 'WO-9999',
        poNumber: 'PO-5600',
        amountApproved: 200000,
        amountSpent: 200000,
        purchaseYear: 2023,
        status: TransactionStatus.ACTUAL_SAP,
        deploymentStatus: DeploymentStatus.COMPLETED,
        budgetType: BudgetType.CAPITAL,
        createdAt: new Date().toISOString(),
    },
    {
        id: uuid(),
        program: 'Enterprise Apps',
        team: 'DevOps',
        category: 'SaaS Subscription',
        nwaNumber: 'NWA-6000',
        projectName: 'Jira Enterprise License',
        woNumber: '',
        poNumber: 'PO-9900',
        amountApproved: 45000,
        amountSpent: 45000,
        purchaseYear: 2024,
        status: TransactionStatus.ACTUAL_SAP,
        deploymentStatus: DeploymentStatus.COMPLETED,
        budgetType: BudgetType.OPERATING,
        createdAt: new Date().toISOString(),
    }
];
